modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/refinedmods/refinedstorage2"
license = "MIT"
[[mods]]
modId = "refinedstorage"
version = "2.0.0-beta.2"
displayName = "Refined Storage"
displayURL = "https://refinedmods.com/refined-storage"
logoFile = "icon.png"
authors = "Refined Mods"
description = '''
Refined Storage is a mass storage mod for Minecraft that offers the player a network-based storage system, allowing them to store items and fluids on a massively expandable device network.
'''
[[dependencies.refinedstorage]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.153,)"
ordering = "NONE"
side = "BOTH"
